appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: DlXSwOjmMi6axFo77IDiyFQP7PvcxUSxKHpyj1GJUw0vd7vXpSUek4p0GLg5xEFQfpAYd5CNGru7y0yLo5ehrx0GKY8djzuf/xap7zQhIEPlP+Ij8D1IqgHFokbaJyqdaZPsTvAwa7ttMYSB4TJJDGNIDLzPRfkrpijJZ9v31ImEKoFM46izkFlO57naHWsE50oCYW2HAWA/6hgU4nuRN+aVmzsfrQE7EfJNFpa2rlybEnz7xREqIQkkd+jlza+vGSB9FrmJxA6wKTaQ+tvInxYjob4iXRuCHg5pWCLIo4CMSfcXYgBoIThy/GyL9B+N+vi/miTUM9acyK+NE+r4TEpV5monhkeiHBFVOpQdaXoshP5/z5d0IT1GSTwOFYhJ2tjUFN1VA06kBLhPIzNmvI4svhDI9EpRbw03+jXRzSee+3Y/Un4rQjz753T68EKFry2vmTqmDwBadrU2zXcgqfTX+pbp2gGeEA0LQYOh8HCoZXG4Gbq6sY4mz38hGFPLu4cC78MCG0k/I50zIvw1z/Qlw4Ws2q9mzGzK2ZX6jFudfK/5E12G4xh2JwCjZ2gh44FeXZlkf697OD371jgrVjvT9g/NMMhzBjRzt2reijdiYJghM0k5YbZd0/CKUxsfzGqWiJUxN39CLLLeGIU35efgRVhW+EJ+rok38MxVwFU=
